package model;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 04 09:28:11 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DepartmentId,
        DepartmentName,
        ManagerId,
        LocationId,
        SelectCheck,
        SelectCheck1,
        SelectCheck2,
        EmployeesVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int SELECTCHECK = AttributesEnum.SelectCheck.index();
    public static final int SELECTCHECK1 = AttributesEnum.SelectCheck1.index();
    public static final int SELECTCHECK2 = AttributesEnum.SelectCheck2.index();
    public static final int EMPLOYEESVO = AttributesEnum.EmployeesVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute DepartmentId.
     * @return the DepartmentId
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Gets the attribute value for the calculated attribute DepartmentName.
     * @return the DepartmentName
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ManagerId.
     * @return the ManagerId
     */
    public Integer getManagerId() {
        return (Integer) getAttributeInternal(MANAGERID);
    }

    /**
     * Gets the attribute value for the calculated attribute LocationId.
     * @return the LocationId
     */
    public Integer getLocationId() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectCheck.
     * @return the SelectCheck
     */
    public Boolean getSelectCheck() {
        return (Boolean) getAttributeInternal(SELECTCHECK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectCheck.
     * @param value value to set the  SelectCheck
     */
    public void setSelectCheck(Boolean value) {
        setAttributeInternal(SELECTCHECK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectCheck1.
     * @return the SelectCheck1
     */
    public Boolean getSelectCheck1() {
        return (Boolean) getAttributeInternal(SELECTCHECK1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectCheck1.
     * @param value value to set the  SelectCheck1
     */
    public void setSelectCheck1(Boolean value) {
        setAttributeInternal(SELECTCHECK1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectCheck2.
     * @return the SelectCheck2
     */
    public Boolean getSelectCheck2() {
        return (Boolean) getAttributeInternal(SELECTCHECK2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectCheck2.
     * @param value value to set the  SelectCheck2
     */
    public void setSelectCheck2(Boolean value) {
        setAttributeInternal(SELECTCHECK2, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeesVO.
     */
    public RowIterator getEmployeesVO() {
        return (RowIterator) getAttributeInternal(EMPLOYEESVO);
    }
}

