package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 03 16:17:45 IST 2019
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void employessList();
}

